# Generated by Django 6.1 on 2026-08-08 05:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('active', models.BooleanField(default=True)),
                ('client_name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='clients/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('status', models.CharField(choices=[('live', 'Live Client'), ('previous', 'Previous Client')], default='live', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Client logos',
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=100)),
                ('service_required', models.CharField(choices=[('fire_alarm', 'Fire Alarm System'), ('cctv', 'CCTV System'), ('access_control', 'Access Control System'), ('pa_system', 'Public Address System'), ('fire_extinguisher', 'Fire Extinguisher'), ('wld_rodent', 'WLD & Rodent'), ('intrusion', 'Intrusion System'), ('vesda', 'VESDA'), ('other', 'Other')], max_length=30)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('closed', 'Closed')], default='new', max_length=12)),
                ('source_page', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('caption', models.CharField(help_text='Maximum 50 characters.', max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('icon_css_class', models.CharField(blank=True, help_text="Optional icon class, e.g. 'bi-fire' (Bootstrap Icons).", max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='team/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('caption', models.CharField(blank=True, help_text='Maximum 50 characters.', max_length=50)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrustCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('active', models.BooleanField(default=True)),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page')], default='home', max_length=10)),
                ('closed_label', models.CharField(help_text="Text shown before the card is opened, e.g. 'TRUST'.", max_length=60)),
                ('headline', models.CharField(help_text="Revealed headline, e.g. '12+ Years of Experience'.", max_length=100)),
                ('detail', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='services/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('brands', models.ManyToManyField(blank=True, related_name='services', to='core.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
